---

- name: Check existence of The Lounge systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ the_lounge_identifier }}.service"
  register: the_lounge_service_stat

- when: the_lounge_service_stat.stat.exists | bool
  block:
    - name: Ensure The Lounge systemd service is stopped
      ansible.builtin.service:
        name: "{{ the_lounge_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure The Lounge systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ the_lounge_identifier }}.service"
        state: absent

    - name: Ensure The Lounge path doesn't exist
      ansible.builtin.file:
        path: "{{ the_lounge_base_path }}"
        state: absent
