---

- name: Fail if required The Lounge settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - the_lounge_identifier
    - the_lounge_uid
    - the_lounge_gid
    - the_lounge_hostname
    - the_lounge_path_prefix
    - the_lounge_container_network

- when: the_lounge_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required The Lounge Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - the_lounge_container_labels_traefik_hostname
        - the_lounge_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `the_lounge_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if the_lounge_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          the_lounge_container_labels_traefik_path_prefix (`{{ the_lounge_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/the_lounge`).
      when: "the_lounge_container_labels_traefik_path_prefix != '/' and the_lounge_container_labels_traefik_path_prefix[-1] == '/'"
